project:
  type: website

website:
  title: "bReaus"
  site-url: https://carluna.github.io/bReaus/
  open-graph:
    title: bReaus - A blog about water and R
    description: This is a place to share our thoughts and experiences with hydrology and R. 
    image: hex-bReaus_final2.png
    locale: de_DE
  favicon: hex-bReaus_final2.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Carluna/bReaus

format:
  html:
    theme: cosmo
    css: styles.css




