project:
  type: website

website:
  title: "bReaus"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Carluna/bReaus

format:
  html:
    theme: cosmo
    css: styles.css



